services:
  - type: web
    name: naavai-ai-f6
    runtime: docker
    dockerfilePath: ./Naavai/Dockerfile
    dockerContext: ./Naavai
    plan: free
    branch: master
    healthCheckPath: /api/v1/health
