"""Board-ready workbook export for a completed shipment analysis."""
from io import BytesIO


def generate_audit_workbook(result: dict, inputs: dict) -> bytes:
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill
    except ModuleNotFoundError as exc:
        raise RuntimeError("Excel export requires openpyxl. Run: python -m pip install -r requirements.txt") from exc
    wb = Workbook()
    summary = wb.active
    summary.title = "Executive Summary"
    rows = [("Generated by", "Naavai AI"),
            ("Route", f"{inputs.get('origin_port')} -> {inputs.get('destination_port')}"),
            ("Cargo (MT)", inputs.get("tonnage")),
            ("Vessel", inputs.get("vessel_class")),
            ("P50 target ($/MT)", result["layer3_ml_forecast"]["P50_recommended_rate"]),
            ("P10 floor ($/MT)", result["layer3_ml_forecast"]["P10_floor"]),
            ("P90 ceiling ($/MT)", result["layer3_ml_forecast"]["P90_ceiling"]),
            ("Port clearance", "APPROVED" if result["layer2_clearance"]["allowed"] else "RESTRICTED"),
            ("Queue wait (days)", result["layer4_queue_demurrage"]["simulated_avg_wait_days"]),
            ("Demurrage exposure ($)", result["layer4_queue_demurrage"]["demurrage"]["demurrage_usd"]),
            ("Recommendation", result["layer5_recommendation"]["contract_mode"])]
    incident = result.get("historical_incident_context")
    if incident:
        rows.extend([("Historical incident", incident.get("title")),
                     ("Verified source", incident.get("source")),
                     ("Historical failure", incident.get("historical_failure")),
                     ("Expected benefit", incident.get("quantified_savings"))])
    for row in rows: summary.append(row)
    summary["A1"].font = Font(bold=True)
    summary.column_dimensions["A"].width = 28
    summary.column_dimensions["B"].width = 65

    flow = wb.create_sheet("Decision Flow")
    flow.append(["Step", "Checkpoint", "Metric", "Status", "Explanation"])
    for cell in flow[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1F4E78")
    for cp in result.get("decision_flow", []):
        flow.append([cp.get("step"), cp.get("cp_label"), cp.get("metric"), cp.get("status"), cp.get("explanation")])
    flow.column_dimensions["E"].width = 100

    portfolio = wb.create_sheet("MILP Assignments")
    assignments = result["layer5_recommendation"]["portfolio_optimization"].get("schedule_assignments", [])
    if assignments:
        headers = list(assignments[0].keys())
        portfolio.append(headers)
        for cell in portfolio[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill("solid", fgColor="1F4E78")
        for item in assignments: portfolio.append([item.get(h) for h in headers])
    else:
        portfolio.append(["No assignments returned"])

    out = BytesIO()
    wb.save(out)
    return out.getvalue()
